import { type LangCode } from '@/store/useSettingsStore';
import { COMMODITY_FRIENDLY } from './bahasa';

/**
 * Terjemahan nama komoditas ke bahasa daerah.
 * Hanya komoditas umum yang diterjemahkan — yang tak ada tetap pakai Indonesianya.
 */
const TR: Record<LangCode, Record<string, string>> = {
  id: {},
  jv: {
    beras_medium: 'Beras Medium',
    beras_premium: 'Beras Premium',
    jagung_pipilan: 'Jagung Pipilan',
    kedelai_kering: 'Kedele Garing',
    cabai_rawit_merah: 'Cabe Rawit Abang',
    cabai_rawit_hijau: 'Cabe Rawit Ijo',
    cabai_merah_besar: 'Cabe Abang Gede',
    cabai_merah_keriting: 'Cabe Abang Kriting',
    bawang_merah: 'Bawang Abang',
    bawang_putih: 'Bawang Putih',
    tomat: 'Tomat',
    kentang: 'Kentang',
    kacang_tanah: 'Kacang Tanah',
    kacang_hijau: 'Kacang Ijo',
    gula_pasir: 'Gula Pasir',
    minyak_goreng_curah: 'Lenthik Goreng Curah',
    minyak_goreng_kemasan: 'Lenthik Goreng Kemasan',
    telur_ayam: 'Endhog Ayam',
    ayam_broiler: 'Ayam Potong',
    sapi_murni: 'Daging Sapi',
    ikan_kembung: 'Ikan Kembung',
    ikan_bandeng: 'Ikan Bandeng',
    ikan_tongkol: 'Ikan Tongkol',
    ikan_lele: 'Ikan Lele',
    ikan_nila: 'Ikan Nila',
    ikan_teri: 'Ikan Teri',
    udang_windu: 'Udang Windu',
    pupuk_urea: 'Pupuk Urea',
    pupuk_npk: 'Pupuk NPK',
    pupuk_sp36: 'Pupuk SP-36',
    pupuk_za: 'Pupuk ZA',
    lpg_3kg: 'Elpiji 3 Kg',
    lpg_12kg: 'Elpiji 12 Kg',
    semen_portland: 'Semen Portland',
    mie_instan: 'Mie Instan',
    garam_halus: 'Uyah Halus',
    beras_sphp: 'Beras SPHP',
    kacang_panjang: 'Kacang Panjang',
    kangkung: 'Kangkung',
    sawi_hijau: 'Sawi Ijo',
    jeruk_lokal: 'Jeruk Lokal',
    pisang_lokal: 'Pisang Lokal',
    susu_bubuk: 'Susu Bubuk',
    susu_kemanis: 'Susu Kental Manis',
  },
  su: {
    beras_medium: 'Beras Medium',
    beras_premium: 'Beras Premium',
    jagung_pipilan: 'Jagung Pipillean',
    kedelai_kering: 'Kacang Jede Kering',
    cabai_rawit_merah: 'Cabe Rawit Beureum',
    cabai_rawit_hijau: 'Cabe Rawit Hejo',
    cabai_merah_besar: 'Cabe Beureum Gede',
    cabai_merah_keriting: 'Cabe Beureum Keriting',
    bawang_merah: 'Bawang Beureum',
    bawang_putih: 'Bawang Bodas',
    tomat: 'Tomat',
    kentang: 'Kentang',
    kacang_tanah: 'Kacang Tanah',
    kacang_hijau: 'Kacang Hejo',
    gula_pasir: 'Gula Pasir',
    minyak_goreng_curah: 'Minyak Goreng Curah',
    minyak_goreng_kemasan: 'Minyak Goreng Kemasan',
    telur_ayam: 'Endog Hayam',
    ayam_broiler: 'Hayam Potong',
    sapi_murni: 'Daging Sapi',
    ikan_kembung: 'Ikan Kembung',
    ikan_bandeng: 'Ikan Bandeng',
    ikan_tongkol: 'Ikan Tongkol',
    ikan_lele: 'Ikan Lele',
    ikan_nila: 'Ikan Nila',
    ikan_teri: 'Ikan Teri',
    udang_windu: 'Udang Windu',
    pupuk_urea: 'Pupuk Urea',
    pupuk_npk: 'Pupuk NPK',
    pupuk_sp36: 'Pupuk SP-36',
    pupuk_za: 'Pupuk ZA',
    lpg_3kg: 'Elpiji 3 Kg',
    lpg_12kg: 'Elpiji 12 Kg',
    semen_portland: 'Semen Portland',
    mie_instan: 'Mie Instan',
    garam_halus: 'Uyah Halus',
    beras_sphp: 'Beras SPHP',
    kacang_panjang: 'Kacang Panjang',
    kangkung: 'Kangkung',
    sawi_hijau: 'Sawi Hejo',
    jeruk_lokal: 'Jeruk Lokal',
    pisang_lokal: 'Pisang Lokal',
    susu_bubuk: 'Susu Bubuk',
    susu_kemanis: 'Susu Kental Manis',
  },
  ms: {
    beras_medium: 'Beras Sederhana',
    beras_premium: 'Beras Premium',
    jagung_pipilan: 'Jagung Pecah',
    kedelai_kering: 'Kacang Soya Kering',
    cabai_rawit_merah: 'Cili Padi Merah',
    cabai_rawit_hijau: 'Cili Padi Hijau',
    cabai_merah_besar: 'Cili Merah Besar',
    cabai_merah_keriting: 'Cili Merah Kriting',
    bawang_merah: 'Bawang Merah',
    bawang_putih: 'Bawang Putih',
    tomat: 'Tomato',
    kentang: 'Kentang',
    kacang_tanah: 'Kacang Tanah',
    kacang_hijau: 'Kacang Hijau',
    gula_pasir: 'Gula Pasir',
    minyak_goreng_curah: 'Minyak Masak Curah',
    minyak_goreng_kemasan: 'Minyak Masak Bungkus',
    telur_ayam: 'Telur Ayam',
    ayam_broiler: 'Ayam Pedaging',
    sapi_murni: 'Daging Lembu',
    ikan_kembung: 'Ikan Kembung',
    ikan_bandeng: 'Ikan Bandeng',
    ikan_tongkol: 'Ikan Tongkol',
    ikan_lele: 'Ikan Lele',
    ikan_nila: 'Ikan Nila',
    ikan_teri: 'Ikan Teri',
    udang_windu: 'Udang Windu',
    pupuk_urea: 'Baja Urea',
    pupuk_npk: 'Baja NPK',
    pupuk_sp36: 'Baja SP-36',
    pupuk_za: 'Baja ZA',
    lpg_3kg: 'Gas Petroleum 3 Kg',
    lpg_12kg: 'Gas Petroleum 12 Kg',
    semen_portland: 'Simen Portland',
    mie_instan: 'Mee Segera',
    garam_halus: 'Garam Halus',
    beras_sphp: 'Beras SPHP',
    kacang_panjang: 'Kacang Panjang',
    kangkung: 'Kangkung',
    sawi_hijau: 'Sawi Hijau',
    jeruk_lokal: 'Limau Tempatan',
    pisang_lokal: 'Pisang Tempatan',
    susu_bubuk: 'Susu Tepung',
    susu_kemanis: 'Susu Pekat Manis',
  },
};

/** Get commodity display name in user's selected language, fallback to Indonesian. */
export function commodityLabel(slug: string, lang: LangCode = 'id'): string {
  const tr = TR[lang]?.[slug];
  if (tr) return tr;
  return COMMODITY_FRIENDLY[slug] ?? slug;
}
